### ISSUE TITLE
偶尔出现的提杆延迟过大问题。

### ISSUE THREAD

**Issue by 43960771** [babalae/genshin-fishing-toy#10]
咬钩与提杆之间的间隔似乎有些大了，导致有些需要快速提杆的鱼会挣脱（目前我遇到这个情况的有炮魨、假龙）。
这两种鱼偶尔需要咬钩之后快速提杆。
目前没注意到其他鱼是否有这种情况。

**Comment by huiyadanli** [comment]
刷新帧率是不是调的太高了

适当调低可以加快提干速度

**Comment by huiyadanli** [comment]
默认的30一般不会出现提杆延迟过大过大。。

如果电脑性能比较差的话，建议继续下调刷新帧率
