### ISSUE TITLE
请问如何修改启动按钮？

### ISSUE THREAD

**Issue by wd4455** [babalae/genshin-fishing-toy#12]
请问如何修改启动F11为其他按键？
最近使用过程中，在隐藏了钓鱼监视框后偶尔不能自动钓鱼了，能否将监视框的位置加个手动输入坐标的地方，记录坐标位置的地方？重置后不用再去对齐。

**Comment by huiyadanli** [comment]
自定义快捷键因为偷懒一直没做。。

监视框的位置会一直自动记录，具体配置在默认保存在 C:\Users\你的用户名\AppData\Local\GenshinAutoFish 下

```xml
<setting name="StrainBarAreaLocation" serializeAs="String">
    <value>562, 56</value>
</setting>
```

**Comment by wd4455** [comment]
怪不得，在xml里翻完了没找到
