### ISSUE TITLE
鱼上钩后，能够自动提竿，但是不会自动钓鱼，提竿后识别框就卡住不动了，手动钓完后识别框又会动

### ISSUE THREAD

**Issue by seepine** [babalae/genshin-fishing-toy#14]
2022/4/7 21:28:51 ┌------------------------┐
2022/4/7 21:28:51   自动提竿
2022/4/7 21:28:54   X 提竿后没有钓鱼，重置!
2022/4/7 21:28:54 └------------------------┘

**Comment by seepine** [comment]
现在复现不了了，原神重启钓鱼机重启几次后，现在可以正常了..

**Comment by seepine** [comment]
![image](https://user-images.githubusercontent.com/93666053/162745906-ca9d8948-990d-4297-9f65-32e14b74cfc2.png)
![image](https://user-images.githubusercontent.com/93666053/162745938-9892b704-17cd-4202-bb00-e7926e034a56.png)

钓鱼机重启也不好使，重新调识别框也不好使

**Comment by seepine** [comment]
![image](https://user-images.githubusercontent.com/93666053/162753401-f8f7781d-fb51-4782-aa43-b7ccf3b34c30.png)
提竿后它就不动了，鱼跑掉后又开始动

**Comment by huiyadanli** [comment]
取消自动提杆功能后能否正常自动钓鱼？

**Comment by seepine** [comment]
也不行，得确保先运行软件，再开游戏才能自动钓
