### ISSUE TITLE
引发类型为System.OutofMemoryException的异常

### ISSUE THREAD

**Issue by Bilx-ZL** [babalae/genshin-fishing-toy#16]
<img width="287" alt="屏幕截图 2022-04-22 135215" src="https://user-images.githubusercontent.com/104142438/164612104-ee065bbb-40fc-4de7-ba53-1605e0a4390c.png">
钓鱼几次后，或者不动过段时间就会出现

正常使用时的内存使用率呈现楼梯状
<img width="535" alt="屏幕截图 2022-04-23 173532" src="https://user-images.githubusercontent.com/104142438/164889105-b88ac0a2-1249-4d0c-aa0f-9aab821ab0cf.png">

报错时的内存使用情况：
<img width="691" alt="屏幕截图 2022-04-23 173600" src="https://user-images.githubusercontent.com/104142438/164889157-3b5d86ed-68c1-4534-8dba-4fd2e8a7d788.png">
<img width="683" alt="屏幕截图 2022-04-23 173637" src="https://user-images.githubusercontent.com/104142438/164889160-dbd67332-1a6e-40f7-bb73-d092a64435b2.png">

**Comment by Bilx-ZL** [comment]
作者能打包成64位软件吗？听说C#有自动内存释放，感觉是撞到4G内存墙了

**Comment by huiyadanli** [comment]
https://ws28.cn/f/85ac4rzerwt 

x64 的打包，试试

**Comment by huiyadanli** [comment]
软件正常内存就是梯状内存释放，可以适当调低自动钓鱼的刷新帧率。。

**Comment by Bilx-ZL** [comment]
> https://ws28.cn/f/85ac4rzerwt
> 
> x64 的打包，试试

长时间确认没有再出现此问题！
