### ISSUE TITLE
尝试打包成单个exe程序时运行报错找不到OpencCvSharpExtern的库

### ISSUE THREAD

**Issue by EDGEXI** [babalae/genshin-fishing-toy#17]
我想打包成一个包含依赖库的单独exe程序，但是运行时开启钓鱼会报错找不到”OpencCvSharpExtern“的dll库，个人能力有限，作者有什么建议吗

**Comment by huiyadanli** [comment]
建议用VS从源码开始打包单文件程序。。。

报错的原因的 OpenCvSharp4 对应的dll没有在程序当前目录下找到

**Comment by EDGEXI** [comment]
源码是指整个解决方案的文件么？
我把dll放在和程序同一个目录下打包还是会报错，不打包的话倒是正常运行。另外我是用vs里的costura.fody打包的，作者有什么好的打包工具建议么？谢谢了

**Comment by EDGEXI** [comment]
解决了，原因是我之前省事没有放32位的库进去，只放了64的
请问下有什么方法可以做成64位的程序么

**Comment by huiyadanli** [comment]
vs项目设置中可以指定只编译x64平台

**Comment by EDGEXI** [comment]
okok谢谢了
