### ISSUE TITLE
能自动提竿，识别到钓鱼框，但是钓不上来。

### ISSUE THREAD

**Issue by cwyuu** [babalae/genshin-fishing-toy#19]
![image](https://user-images.githubusercontent.com/95075881/171050496-c824e5fa-dffb-4303-ae7f-e7b90730cfd7.png)
![image](https://user-images.githubusercontent.com/95075881/171050610-dba2b4ff-0fb4-4cbb-a305-ce083d27525a.png)

**Comment by huiyadanli** [comment]
看上去是权限不足，是否以管理员权限启动了自动钓鱼软件
