### ISSUE TITLE
建议加入选项：上钩后才检测钓鱼框

### ISSUE THREAD

**Issue by SpringWhisper** [babalae/genshin-fishing-toy#20]
开着钓鱼机跑图，仍会出现误识别钓鱼框导致按下左键的情况。目前发现在下落攻击挖石珀时经常出现误识别。
能否加入复选框，让程序必须识别到上钩后，才检测钓鱼框？这样能大幅降低误识别概率。

**Comment by huiyadanli** [comment]
![image](https://user-images.githubusercontent.com/15783049/180212390-21dc996e-a1bd-43a6-adf7-96394afd2363.png)

是已知问题。加入这个选项选择以后，上钩判定万一出错就不能正常钓鱼了...

**Comment by 1164844282** [comment]
那么能多检测一个区域吗比如先检测这个图标判断是否进入钓鱼模式
![图片](https://user-images.githubusercontent.com/52785205/194736843-dc5a186e-04fe-41b9-92ec-854974ec3137.png)
再出现鱼上钩的这个图标后
![图片](https://user-images.githubusercontent.com/52785205/194736820-03f84e27-be04-4cd6-ac57-2799f9466d5f.png)
开始钓鱼

**Comment by 1164844282** [comment]
> ![image](https://user-images.githubusercontent.com/15783049/180212390-21dc996e-a1bd-43a6-adf7-96394afd2363.png)
> 
> 是已知问题。不过加入这个选项选择以后，上钩判定万一出错就不能正常钓鱼了...

那么能多检测一个区域吗比如先检测这个图标判断是否进入钓鱼模式
![图片](https://user-images.githubusercontent.com/52785205/194736873-3dbb563f-30c3-406c-8fe5-ce648ce17a53.png)
再出现鱼上钩的这个图标后开始钓鱼
![图片](https://user-images.githubusercontent.com/52785205/194736883-fd639378-98f4-4215-884b-7788ef12fe10.png)
