### ISSUE TITLE
蒙德钓鱼框位置不同导致识别问题

### ISSUE THREAD

**Issue by SpringWhisper** [babalae/genshin-fishing-toy#21]
这是璃月和稻妻的钓鱼框的位置，靠下
![璃月和稻妻的钓鱼框的位置](https://user-images.githubusercontent.com/48538969/180224021-8482f573-1f59-428d-9e67-b6184a981c68.png)
这是蒙德钓鱼框的位置，靠上
![蒙德钓鱼框的位置](https://user-images.githubusercontent.com/48538969/180224393-5690ed30-8e48-4ad3-953d-8ef4682f347f.png)
为了兼顾两种钓鱼框的位置，识别框设置的比较高。但此时，在蒙德钓鱼时，钓鱼机会识别到钓鱼框下方的钓鱼进度条，导致自动拉扯异常。
![识别到钓鱼进度条](https://user-images.githubusercontent.com/48538969/180225141-4fc46a50-b7db-47b7-a059-ffae7bf7ae1f.png)

可以在更换区域时手动重新调整识别框，但是比较麻烦，能不能通过软件解决？
下面是我的想法：
方案一：可以自定义多个识别框的位置，以便在钓鱼机内切换位置。
方案二：识别钓鱼进度条的鱼钩符号，把它周围一定区域设定为安全区，安全区内不识别钓鱼框。

**Comment by huiyadanli** [comment]
不科学，我记得只有上方出现了什么提示才会把钓鱼条压下来。

你是不是当天升级过 ，纯传送是不会影响钓鱼条的位置的

**Comment by SpringWhisper** [comment]
重装游戏后，钓鱼条位置正常了。
之前没有升级，不知道为什么钓鱼条会向下。
