### ISSUE TITLE
鱼咬钩后的拉竿阶段经常会脱离黄色的框死按到最右边

### ISSUE THREAD

**Issue by qiuyue1126** [babalae/genshin-fishing-toy#22]
鱼咬钩后的拉竿阶段经常会脱离黄色的框死按到最右边,但过一会又会回到框内,也不是钓不了,就是有点拖时间

**Comment by qiuyue1126** [comment]
![image](https://user-images.githubusercontent.com/77103327/183061211-58ea0df8-af18-40eb-9f96-667f8a8a5df8.png)

**Comment by huiyadanli** [comment]
![image](https://user-images.githubusercontent.com/15783049/183102587-b06ff51d-6c42-4bc5-ba19-513e4b11b2b9.png)

不要框住下方的钓鱼总进度圈
不要框住下方的钓鱼总进度圈
不要框住下方的钓鱼总进度圈
