### ISSUE TITLE
钓鱼的识别有问题，他会一直加力气，无法减力气

### ISSUE THREAD

**Issue by KUILINGWU** [babalae/genshin-fishing-toy#24]
![image](https://user-images.githubusercontent.com/90816048/186138900-bcf666f6-12ff-44ca-9188-38cd3badd2b1.png)
软件没有以前灵活了，问题是，在识别后迟钝，识别栏和移动栏不匹配了，导致识别栏向左移动，移动栏还加力气向右，而且是一直登顶

**Comment by huiyadanli** [comment]
你框选的区域有问题

**不要框住下方的钓鱼总进度圈
不要框住下方的钓鱼总进度圈
不要框住下方的钓鱼总进度圈**
