### ISSUE TITLE
全屏模式下无法自动提竿，自动拉扯功能正常

### ISSUE THREAD

**Issue by NOWorEVER** [babalae/genshin-fishing-toy#27]
全屏模式下无法自动提竿，自动拉扯功能正常
windows11，给管理员权限了
![image](https://github.com/babalae/genshin-fishing-toy/assets/57054154/9f040480-79da-4f9d-b5b4-c5ad63592c2e)

**Comment by NOWorEVER** [comment]
![image](https://github.com/babalae/genshin-fishing-toy/assets/57054154/4a117fdb-0e20-490a-9703-b5c623dc7181)

**Comment by huiyadanli** [comment]
勾选显示识别窗口截图

**Comment by NOWorEVER** [comment]
我这识别框是放的位置应该没错。拉条功能是正常的。但是还是不提钩子
![image](https://github.com/babalae/genshin-fishing-toy/assets/57054154/fbe3b416-60ab-4852-b81d-46d1b3382d07)
![image](https://github.com/babalae/genshin-fishing-toy/assets/57054154/70d4cc7d-7475-44bd-ad76-8c0b0b6f691a)
窗口化是可以正常拉绳子的
![image](https://github.com/babalae/genshin-fishing-toy/assets/57054154/018c86e8-c743-480f-9c46-1c4f63afa3d8)

**Comment by huiyadanli** [comment]
上边缘往上设置一点就行了

**Comment by NOWorEVER** [comment]
懂了，感谢，边框拾取高度设置高就好了
