### ISSUE TITLE
提竿的延迟有点长

### ISSUE THREAD

**Issue by 1055169799** [babalae/genshin-fishing-toy#4]
一般人工钓鱼虽然不是瞬间秒提竿，但总体还是在一秒内提竿的，软件的提高延迟过大了，经常会导致钓鱼没提竿而失败

![Z3P@6CF53FXAIVX31D5ZXBI.png](https://user-images.githubusercontent.com/41286675/147869095-bd684d6c-3282-4dac-90ca-4ccaccc9833d.png)

**Comment by huiyadanli** [comment]
帧率调整到30试试，跟程序的处理速度也有关

**Comment by 1055169799** [comment]
> 帧率调整到30试试，跟程序的处理速度也有关
> 

好的
