### ISSUE TITLE
一条都钓不到

### ISSUE THREAD

**Issue by shutdown1210** [babalae/genshin-fishing-toy#7]
识别框已经识别到进度条位置，模拟鼠标控制一直不正常**
![image](https://user-images.githubusercontent.com/47078289/150689235-6d46fb7a-f80a-4df7-9c35-8257b12fc2fb.png)
**z

**Comment by shutdown1210** [comment]
每次都在最左或者最右

**Comment by huiyadanli** [comment]
你的选区太大了，只需要框住钓鱼进度条就可以了，**不要框住下方的钓鱼总进度圈**
