### ISSUE TITLE
自动提竿功能是需要用识别框把右下角也框住么

### ISSUE THREAD

**Issue by MomentDerek** [babalae/genshin-fishing-toy#8]
readme里好像只是说框钓鱼条

**Comment by MomentDerek** [comment]
总的来说非常好用，多谢大佬

**Comment by huiyadanli** [comment]
不需要框选右下角，自动提杆没用到右下角的图标

**Comment by MomentDerek** [comment]
看到了，是使用文字提示作为识别对象的，但是似乎很多时候根本不识别，连debug用的识别窗口都没有弹出
![image](https://user-images.githubusercontent.com/40252940/154856300-0da0f9ef-9662-4cb6-b44d-2ed18807b1f5.png)

**Comment by huiyadanli** [comment]
的确是通过钓鱼那块文字区域来进行识别的。。。但是并不是去真正识别那块文本，只是判断了出现了白色文字的选区而已。。

**Comment by nomoneynolife** [comment]
现在是手动下杆，手动提杆。

> 自动提杆没用到右下角的图标

自动提杆 
鱼上钩后提示文字的位置，处于进度条下方圆形的位置，如果一框选会影响钓鱼的准确性
能否把自杆的选取独立出来，

**Comment by huiyadanli** [comment]
钓鱼进度条的款选区域太小也有可能导致提杆没法正常识别。。

**Comment by nomoneynolife** [comment]
不知道是不是分辨率的问题，我现在分辨率是1024*768
假设分辨率大一点的话。
框选的位置不会覆盖进度条下面的圆形进度条，而恰好包含提杆的提示

**Comment by huiyadanli** [comment]
@nomoneynolife 那可以把选取上边缘调高，下边缘还是不能覆盖到圆形进度条。这样应该就可以正常提杆了。因为钓鱼那块文字区域我这边写死是向下取当前选区的高度*2。。。在某些分辨率下的确可能有问题。。。

**Comment by nomoneynolife** [comment]
@huiyadanli 完美了
