### ISSUE TITLE
进全屏模式识别框就无法置顶了咋办

### ISSUE THREAD

**Issue by 2413228399** [babalae/genshin-fishing-toy#9]
Uploading QQ录屏20220208214425.mp4…

**Comment by huiyadanli** [comment]
部分人的确会存在这种情况。。。暂时没有什么解决方案，只能切换为窗口模式。。

**Comment by 2413228399** [comment]
好的，谢谢大佬




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年2月8日(星期二) 晚上10:51
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [babalae/genshin-fishing-toy] 进全屏模式识别框就无法置顶了咋办 (Issue #9)





 
部分人的确会存在这种情况。。。暂时没有什么解决方案，只能切换为窗口模式。。
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
